services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: backend
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    restart: on-failure:5