version: "1.0"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: purrcast-backend
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: purrcast-frontend
    restart: no
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
