# fly.toml app configuration file generated for purrcast-api on 2023-12-08T14:02:51-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "purrcast-api"
primary_region = "sea"

[build]
  build-target = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[vm]]
  cpu_kind = "shared"
  cpus = 4
  memory_mb = 2048
  
[env]
  NODE_ENV = "production"
