name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy_migrations_to_prod:
    name: Deploy Prisma Migrations to Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v3
        
      - name: Deploy Prisma Migs to Prod
        run:  npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        working-directory: ./backend
  
  deploy:
    name: Deploy API to Fly.io
    runs-on: ubuntu-latest
    needs: deploy_migrations_to_prod
    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v3
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        working-directory: ./backend
